version: "3.8"
services:
  dask-gateway-server-osparc:
    image: local/dask-gateway-server-osparc:${BUILD_TARGET:?build_target_required}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - local/dask-gateway-server-osparc:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-gateway-server-osparc:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-gateway-server-osparc:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-gateway-server-osparc:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"