version: '2.3' # Don't touch
services:
  dask-gateway-server-osparc:
    image: local/dask-gateway-server-osparc:${BUILD_TARGET:?build_target_required}
    deploy:
      endpoint_mode: dnsrr
    ports:
      - "8001:8000"
    volumes:
      - ./dask-gateway-server:/devel/services/dask-gateway-server
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dask_net

networks:
  dask_net:
    driver: bridge
    attachable: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "172.9.0.0/16"